import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="/static/css/styles.css"/> */}
        {/* <link rel="stylesheet" href="/static/css/bishrelt.min.css"/> */}
        {/* <link rel="stylesheet" href="/static/css/gallery_styles.css"/> */}
        {/* <link rel="stylesheet" href="/static/css/reset.css"/> */}
        <link rel="stylesheet" href="/static/css/jqueryslidemenu.css" />
        <link rel="stylesheet" href="/static/css/slideshow.css"/>
        <link rel="stylesheet" href="/static/css/responsive.css"/>
        <link rel="stylesheet" href="/static/assets/main.css"/>


      {/* <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossOrigin="anonymous"
        /> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
 
      </head>
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>

        </body>
    </html>
  );
}
